### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by epinault** [joshuataylor/snowflake_elixir#3]
Hello! 

I am playing with this lib, I am not quite sure where the entry point is . I suspect that the child_spec in the SnowflakeEx is
when using 
```
DBConnection.start_link(SnowflakeEx, 
  [host: "myhost",
  username: "myuser",
  password: "mypass",
  account_name: "account",
  database: "db_name"]
)
```

but I am getting a strange error

```
(RuntimeError) connect raised UndefinedFunctionError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (snowflake_elixir 0.1.0) SnowflakeEx.connect/1
    (db_connection 2.3.0) lib/db_connection/connection.ex:81: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Seems like the child_spec return a DBConnection spec using the SnowflakEx.Protocol, which then start a Gen server for the SnowflakeExConnectionServer?  What am I missing?

**Comment by epinault** [comment]
I have tried with this and seems like I am getting something
```
DBConnection.start_link(SnowflakeEx.Protocol,
  [host: "myhost",
  username: "myuser",
  password: "mypass",
  account_name: "account",
  database: "db_name"]
)
```

I now get a pid. is that expected? I am ensure how your child_spec in SnowflakeEx is suppose to be used unless this is for making a supervisor ?

Now trying to figure out how to use also your query API as I see a token in the state but a different error as well

SnowflakeEx.prepare_execute(pid, "yo", "SELECT ?", [42])

```
no function clause matching in SnowflakeEx.SnowflakeConnectionServer.handle_call/3
    (snowflake_elixir 0.1.0) lib/snowflake_elixir/snowflake_connection_server.ex:77: SnowflakeEx.SnowflakeConnectionServer.handle_call({:select_query, "SELECT ?", '*', []},  <the state details and I see a token in here>
     (stdlib 3.12.1) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib 3.12.1) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
````=

**Comment by joshuataylor** [comment]
Hi!

Thanks so much for checking out the library! This is pretty early (as you can tell) and still needs a cleanup, but I believe that this can awesome library for working with Snowflake. :rocket: 

With dbconnection, you should be supervising in your application so it'll restart incase of failures. Documentation for usage around this will definitely be something we want to improve ASAP.

**Comment by epinault** [comment]
yea sounds good! I spent time reading about db connection and how it used (looking at the source code and blog post they have) . Definitely works well. I think just updating the Readme on how to use it would be great. I ll see if I can send you a PR shortly

**Comment by epinault** [comment]
I created PR #6 to help a bit
