### ISSUE TITLE
IEX left over

### ISSUE THREAD

**Issue by epinault** [joshuataylor/snowflake_elixir#4]
https://github.com/joshuataylor/snowflake_elixir/blob/fd80fe8975267a98dc0377175cf77073ef178a16/lib/snowflake_elixir/http/snowflake_client.ex#L115

I think this is going to be a problem left as is. Would it be possible to remove those line from this code?

**Comment by joshuataylor** [comment]
Great spot, will also trawl the codebase to ensure no debug/development code is found.

**Comment by epinault** [comment]
just merge #5 to detect things like that in the future
