### ISSUE TITLE
Token expires

### ISSUE THREAD

**Issue by epinault** [joshuataylor/snowflake_elixir#7]
couple of suggestion

1. the login should not be part of the init of a process but instead in the handle_continue
2. The token can expire and when it does, then all request will fail with no way to update the token. 
3. I wonder if DB connection handle specific error for login/retry failure/disconnection? 

My only choice with current implementation is to kill the process. It would be nice to have a handle_call to force refreshing the token when that happens

**Comment by epinault** [comment]
one way to fix the #2 , just schedule a login or test for connection once in a while an refresh the token automatically

Also would still need to be able to handle a query happening and failing for a session error and do a quick retry for that one or bubble up if not

**Comment by joshuataylor** [comment]
Yep. Sorry for the delay on getting the other issues looked at. Hoping to
find time ASAP to finish up this library.

**Comment by epinault** [comment]
looks like this is dead so closing the issue as I don t need it anymore
